mkdir abstracts
mkdir base
mkdir components
mkdir layout
mkdir pages
mkdir themes
mkdir vendors
cd abstracts
touch _variables.scss
touch _function.scss
touch _mixins.scss
touch _placeholders.scss
cd .. 
cd base 
touch _animations.scss
touch _typography.scss
touch _utilities.scss
touch _reset.scss
cd ..
cd components
touch _buttons.scss
touch _carousel.scss
touch _cover.scss
touch _dropdown.scss
cd ..
cd layout
touch _navigation.scss
touch _grid.scss
touch _header.scss
touch _footer.scss
touch _sidebar.scss
touch _forms.scss
cd ..
cd pages
touch _home.scss
touch _contact.scss
cd ..
cd themes
touch _theme.scss
touch _admin.scss
cd ..
cd vendors
touch _bootstrap.scss
touch _jquery.scss